// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRRHH.Data;

namespace SistemaRRHH.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16");

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaTermino")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPersona")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sueldo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorHoraExtra")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPersona")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MontoHorasExtra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MontoSueldo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdPersona");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rut")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Contrato", b =>
                {
                    b.HasOne("SistemaRRHH.Data.Entities.Persona", "Persona")
                        .WithOne("Contrato")
                        .HasForeignKey("SistemaRRHH.Data.Entities.Contrato", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Pago", b =>
                {
                    b.HasOne("SistemaRRHH.Data.Entities.Persona", "Persona")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
