// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMantencion.Data;

namespace SistemaMantencion.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210708181449_Initial_Database")]
    partial class Initial_Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Mantencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Mantenciones");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.MantencionMaterial", b =>
                {
                    b.Property<int>("MantencionId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("MantencionId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Mantencion_Material");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.MantencionTecnico", b =>
                {
                    b.Property<int>("MantencionId")
                        .HasColumnType("int");

                    b.Property<string>("TecnicoRut")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.HasKey("MantencionId", "TecnicoRut");

                    b.HasIndex("TecnicoRut");

                    b.ToTable("Mantencion_Tecnico");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Tecnico", b =>
                {
                    b.Property<string>("Rut")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rut");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Anho")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Mantencion", b =>
                {
                    b.HasOne("sistema_mantenciones.Data.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Mantenciones")
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.MantencionMaterial", b =>
                {
                    b.HasOne("sistema_mantenciones.Data.Entities.Mantencion", "Mantencion")
                        .WithMany("MantencionProductos")
                        .HasForeignKey("MantencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_mantenciones.Data.Entities.Material", "Material")
                        .WithMany("MantencionesMateriales")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mantencion");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.MantencionTecnico", b =>
                {
                    b.HasOne("sistema_mantenciones.Data.Entities.Mantencion", "Mantencion")
                        .WithMany("MantencionEmpleados")
                        .HasForeignKey("MantencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_mantenciones.Data.Entities.Tecnico", "Tecnico")
                        .WithMany("MantencionesEmpleado")
                        .HasForeignKey("TecnicoRut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mantencion");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Mantencion", b =>
                {
                    b.Navigation("MantencionEmpleados");

                    b.Navigation("MantencionProductos");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Material", b =>
                {
                    b.Navigation("MantencionesMateriales");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Tecnico", b =>
                {
                    b.Navigation("MantencionesEmpleado");
                });

            modelBuilder.Entity("sistema_mantenciones.Data.Entities.Vehiculo", b =>
                {
                    b.Navigation("Mantenciones");
                });
#pragma warning restore 612, 618
        }
    }
}
