// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRRHH.Data;

namespace SistemaRRHH.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210713003213_AddHorasTrabajo")]
    partial class AddHorasTrabajo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaTermino")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPersona")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sueldo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorHoraExtra")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.HorasTrabajadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("Horas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPersona")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Horas_Trabajadas");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rut")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Contrato", b =>
                {
                    b.HasOne("SistemaRRHH.Data.Entities.Persona", "Persona")
                        .WithOne("Contrato")
                        .HasForeignKey("SistemaRRHH.Data.Entities.Contrato", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.HorasTrabajadas", b =>
                {
                    b.HasOne("SistemaRRHH.Data.Entities.Persona", "Persona")
                        .WithMany("HorasTrabajadas")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SistemaRRHH.Data.Entities.Persona", b =>
                {
                    b.Navigation("Contrato");

                    b.Navigation("HorasTrabajadas");
                });
#pragma warning restore 612, 618
        }
    }
}
